-- Production security apply order (review checklist)
-- Apply each file with:
--   npx supabase db query --linked -f supabase/<file>.sql
--
-- Schema prerequisites (safe / idempotent; required before org Settings save):
--   org-footer-image.sql             -- organizations.footer_image_url
--   org-social-links.sql             -- organizations.social_*_url
--   org-favicon.sql                  -- organizations.favicon_url
--
-- 1. revoke-dangerous-grants.sql     -- CRITICAL: revoke run_sql from clients
-- 2. rls-tenant-hardening.sql        -- tighten organizations/profiles SELECT;
--                                    -- drop anon facility/contract catalog SELECT;
--                                    -- public share RPCs (get_public_org_sheet / get_public_program_sheet)
-- 3. save-facility-with-contracts.sql  -- includes update_organization_profile
-- 4. stripe-webhook-events.sql
-- 5. approved-personal-emails.sql
-- 6. security-hardening.sql
-- 7. access-request-intake-hardening.sql
-- 8. column-write-locks.sql          -- P0 privileged-column triggers + stamp_facility_verified
--                                    -- also revokes freeze_stale_facilities from anon/authenticated
-- 9. membership-rpc-only.sql         -- members/invites SELECT-only + invite/remove RPCs
-- 10. freeze-stale-facilities.sql    -- freeze RPC body + revoke anon EXECUTE; schedule separately
-- 11. security-followup-20260823.sql -- billing column REVOKE + get_organization_billing;
--                                    -- billing INSERT lock; preferred_provider lock;
--                                    -- due-list auth; posts/likes tenant SELECT;
--                                    -- get_public_program_sheet requires org.verified
--
-- Read-only apply check (does not write):
--   inspect-live-security.sql
--
-- Live policy inventory snapshot:
--   supabase/migrations/00000000000000_rls_policy_snapshot.json (75 policies)
--   Snapshot may lag applied SQL. Re-run inspect-live-security.sql after apply.
--
-- After deploy, configure Supabase Auth Hook → Before User Created:
--   HTTPS URL: https://www.centerlinked.com/api/auth-before-user-created
--   Secret env: BEFORE_USER_CREATED_HOOK_SECRET
--   Dashboard → Authentication → Hooks → Before User Created. Cannot be verified from git.
--
-- This file is documentation-only (no executable statements).
SELECT 1;
